### ISSUE TITLE
Dependencies broken for submodules

### ISSUE THREAD

**Issue by silizium** [samhocevar/lolremez#10]
> git submodule update --init --recursive
Cloning into '/home/hanno/src/linux/science/lolremez/lol/src/private/nx'...
remote: Repository not found.
fatal: repository 'https://github.com/samhocevar/lol-nx.git/' not found
fatal: clone of 'https://github.com/samhocevar/lol-nx.git' into submodule path '/home/hanno/src/linux/science/lolremez/lol/src/private/nx' failed
Failed to clone 'src/private/nx'. Retry scheduled
Cloning into '/home/hanno/src/linux/science/lolremez/lol/src/private/nx'...
remote: Repository not found.
fatal: repository 'https://github.com/samhocevar/lol-nx.git/' not found
fatal: clone of 'https://github.com/samhocevar/lol-nx.git' into submodule path '/home/hanno/src/linux/science/lolremez/lol/src/private/nx' failed
Failed to clone 'src/private/nx' a second time, aborting
Failed to recurse into submodule path 'lol'

Did you remove the archives from your repository?

**Comment by samhocevar** [comment]
This (`nx`) is a private repository because it contains code under NDA (for the Nintendo Switch) and git appears to be unable to handle ”optional” submodules. I recently got rid of that reference so the fix will be easy.

**Comment by samhocevar** [comment]
Thanks for reporting this!

**Comment by silizium** [comment]
Thank you very much for the swift repair. That was great! I found the reference to "lol" and also found an other github, but I guess this was concerning other users, too. Really great work! Thanks!
