### ISSUE TITLE
Error: Assertion `thread::has_threads()' failed.

### ISSUE THREAD

**Issue by baugigi** [samhocevar/lolremez#11]
Compiled and installed with no error, but when I try to run lolremez I get 

`lolremez: ../lol/include/lol/private/sys/threading.h:170: T lol::queue<T, N>::pop() [with T = int; int N = 128]: Assertion 'thread::has_threads()' failed.`

What's happening?

My machine:
Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Comment by samhocevar** [comment]
Thanks for reporting this. I fixed the problem in commit 6c6636f0f5ec629df17e2fc0e9a37a0a31e1d065. The fix will be in the next release.
