### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by vivienlonde** [samhocevar/lolremez#17]
Thanks for the great tool !

I don't manage to build the solution in Visual Studio. When building, I get lots of errors such as "cannot open source file "assert.h" ".
I am using Visual Studio 2019.
I also have this warning : "Platform 'ORBIS' referenced in the project file 'lolremez' cannot be found.".

**Comment by samhocevar** [comment]
Did you get all submodules recursively as explained in `README.md`?

(note: platform “ORBIS” is a code name for the PlayStation 4, so you can safely ignore the warning if you do not have development tools for that platform)

**Comment by vivienlonde** [comment]
Ok thanks !
Yes I did : "git submodule update --init --recursive"

Switching from VS 2019 to VS 2017 made the build work.
Thank you again
