### ISSUE TITLE
SLN File no longer compiles

### ISSUE THREAD

**Issue by freeone3000** [samhocevar/lolremez#20]
The SLN file appears to be missing a reference to the lol/ directory as an include directory. In addition, the Win8.1 SDK (in contrast with the Win10 SDK) does not include float.h. As such, the project does not compile. I've attempted to retarget against Win10 SDK with build tools 137, but this did not solve the issue.

**Comment by samhocevar** [comment]
Thanks for reporting this. Unfortunately Visual Studio is not very smart and doesn’t understand that retargeting the project requires modifying `Directory.Build.props` rather than `lolremez.vcxproj`. I’ve fixed the issue in d0e62f84f44f8416e625865dad2ecdf0074f4ca0.

**Comment by vivienlonde** [comment]
Thanks for the fix. The reference to build tools v143 in <code>lolremez.vcxproj</code> versus v142 in <code>Directory.Build.props</code> made the project not compile on my machine (windows). Referring to v142 everywhere fixed it.
