### ISSUE TITLE
feature request: erfc() and expm1()

### ISSUE THREAD

**Issue by MathGeniusJodie** [samhocevar/lolremez#21]
would it be possible to add functions like erfc and expm1 for extra precision around zero?

**Comment by samhocevar** [comment]
I can easily add `expm1`, yes. However I have been unable to find a good way to compute `erfc` so far, the formulae I found were either incredibly slow or inaccurate.

**Comment by MathGeniusJodie** [comment]
awesome, shame about erfc, I'm making a math library and I've been finding it hard to approximate it

**Comment by samhocevar** [comment]
Hi! I have added `expm1` and `log1p` to the `main` branch.

I’ll have another look at `erfc`.

**Comment by samhocevar** [comment]
Hi! I have added the `erfc()` and `erfcx()` functions. So I’ll be closing this issue.

Maybe the accuracy issues in `erfc()` will not be a big deal to you; the maximum error is 1.6e-44 (see [this issue](https://github.com/lolengine/lol/issues/2)).
