### ISSUE TITLE
Release 0.4 exe needs explicit stdout/stderr redirect

### ISSUE THREAD

**Issue by jlauha** [samhocevar/lolremez#3]
Running lolremez.exe doesn't seem to "do" anything unless one explicitly redirects the stdout (and stderr).

This works but one has to inspect the txt files afterwards manually:
lolremez >stdout.txt 2>stderr.txt

**Comment by samhocevar** [comment]
I know this is a very ancient bug, but I ensured the latest release (0.7) works properly in both `cmd.exe` and Powershell.
