### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ghost** [samhocevar/lolremez#9]
Hello, i can't quite understand how to compile this project
i tried make command with the makefile.am as input but it tried to use some file in the lol folder which is empty

**Comment by samhocevar** [comment]
It uses git submodules. You will need to retrieve the submodules using your Git client. If you are using the command line:

    git submodule update --init --recursive

**Comment by ghost** [comment]
thanks you for your answer, managed to download the whole lol directory using the command but using 
`make -f Makefile.am`  
in the lolremez directory still gives me 
`Makefile.am:2: /lol/build/autotools/common.am: No such file or directory
make: *** No rule to make target '/lol/build/autotools/common.am'.  Stop.`

i'm sorry i'm a complete newcommer to command line compilation

**Comment by samhocevar** [comment]
You need to first run `./bootstrap` and `./configure` before `make`.

I have now added build instructions to the `README.md`!
